package com.mytribe.db.entity.strategy;

import java.math.BigDecimal;

public class BuildingTypeTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_buildingtype.BuildingTypeID
	 * @mbggenerated
	 */
	private Integer buildingtypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_buildingtype.Name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_buildingtype.SizeLength
	 * @mbggenerated
	 */
	private Integer sizelength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_buildingtype.SizeWidth
	 * @mbggenerated
	 */
	private Integer sizewidth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_buildingtype.AffectRadius
	 * @mbggenerated
	 */
	private BigDecimal affectradius;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_buildingtype.Icon
	 * @mbggenerated
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_buildingtype.Model
	 * @mbggenerated
	 */
	private String model;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_buildingtype.ItemID
	 * @mbggenerated
	 */
	private Integer itemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_buildingtype.Description
	 * @mbggenerated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_buildingtype.BuildingTypeID
	 * @return  the value of mt_s_buildingtype.BuildingTypeID
	 * @mbggenerated
	 */
	public Integer getBuildingtypeid() {
		return buildingtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_buildingtype.BuildingTypeID
	 * @param buildingtypeid  the value for mt_s_buildingtype.BuildingTypeID
	 * @mbggenerated
	 */
	public void setBuildingtypeid(Integer buildingtypeid) {
		this.buildingtypeid = buildingtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_buildingtype.Name
	 * @return  the value of mt_s_buildingtype.Name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_buildingtype.Name
	 * @param name  the value for mt_s_buildingtype.Name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_buildingtype.SizeLength
	 * @return  the value of mt_s_buildingtype.SizeLength
	 * @mbggenerated
	 */
	public Integer getSizelength() {
		return sizelength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_buildingtype.SizeLength
	 * @param sizelength  the value for mt_s_buildingtype.SizeLength
	 * @mbggenerated
	 */
	public void setSizelength(Integer sizelength) {
		this.sizelength = sizelength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_buildingtype.SizeWidth
	 * @return  the value of mt_s_buildingtype.SizeWidth
	 * @mbggenerated
	 */
	public Integer getSizewidth() {
		return sizewidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_buildingtype.SizeWidth
	 * @param sizewidth  the value for mt_s_buildingtype.SizeWidth
	 * @mbggenerated
	 */
	public void setSizewidth(Integer sizewidth) {
		this.sizewidth = sizewidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_buildingtype.AffectRadius
	 * @return  the value of mt_s_buildingtype.AffectRadius
	 * @mbggenerated
	 */
	public BigDecimal getAffectradius() {
		return affectradius;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_buildingtype.AffectRadius
	 * @param affectradius  the value for mt_s_buildingtype.AffectRadius
	 * @mbggenerated
	 */
	public void setAffectradius(BigDecimal affectradius) {
		this.affectradius = affectradius;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_buildingtype.Icon
	 * @return  the value of mt_s_buildingtype.Icon
	 * @mbggenerated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_buildingtype.Icon
	 * @param icon  the value for mt_s_buildingtype.Icon
	 * @mbggenerated
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_buildingtype.Model
	 * @return  the value of mt_s_buildingtype.Model
	 * @mbggenerated
	 */
	public String getModel() {
		return model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_buildingtype.Model
	 * @param model  the value for mt_s_buildingtype.Model
	 * @mbggenerated
	 */
	public void setModel(String model) {
		this.model = model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_buildingtype.ItemID
	 * @return  the value of mt_s_buildingtype.ItemID
	 * @mbggenerated
	 */
	public Integer getItemid() {
		return itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_buildingtype.ItemID
	 * @param itemid  the value for mt_s_buildingtype.ItemID
	 * @mbggenerated
	 */
	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_buildingtype.Description
	 * @return  the value of mt_s_buildingtype.Description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_buildingtype.Description
	 * @param description  the value for mt_s_buildingtype.Description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}