package com.mytribe.db.entity.strategy;

import java.util.ArrayList;
import java.util.List;

public class EquipForgeTemplateExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public EquipForgeTemplateExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andEquipidIsNull() {
			addCriterion("EquipID is null");
			return (Criteria) this;
		}

		public Criteria andEquipidIsNotNull() {
			addCriterion("EquipID is not null");
			return (Criteria) this;
		}

		public Criteria andEquipidEqualTo(Integer value) {
			addCriterion("EquipID =", value, "equipid");
			return (Criteria) this;
		}

		public Criteria andEquipidNotEqualTo(Integer value) {
			addCriterion("EquipID <>", value, "equipid");
			return (Criteria) this;
		}

		public Criteria andEquipidGreaterThan(Integer value) {
			addCriterion("EquipID >", value, "equipid");
			return (Criteria) this;
		}

		public Criteria andEquipidGreaterThanOrEqualTo(Integer value) {
			addCriterion("EquipID >=", value, "equipid");
			return (Criteria) this;
		}

		public Criteria andEquipidLessThan(Integer value) {
			addCriterion("EquipID <", value, "equipid");
			return (Criteria) this;
		}

		public Criteria andEquipidLessThanOrEqualTo(Integer value) {
			addCriterion("EquipID <=", value, "equipid");
			return (Criteria) this;
		}

		public Criteria andEquipidIn(List<Integer> values) {
			addCriterion("EquipID in", values, "equipid");
			return (Criteria) this;
		}

		public Criteria andEquipidNotIn(List<Integer> values) {
			addCriterion("EquipID not in", values, "equipid");
			return (Criteria) this;
		}

		public Criteria andEquipidBetween(Integer value1, Integer value2) {
			addCriterion("EquipID between", value1, value2, "equipid");
			return (Criteria) this;
		}

		public Criteria andEquipidNotBetween(Integer value1, Integer value2) {
			addCriterion("EquipID not between", value1, value2, "equipid");
			return (Criteria) this;
		}

		public Criteria andItemidIsNull() {
			addCriterion("ItemID is null");
			return (Criteria) this;
		}

		public Criteria andItemidIsNotNull() {
			addCriterion("ItemID is not null");
			return (Criteria) this;
		}

		public Criteria andItemidEqualTo(Integer value) {
			addCriterion("ItemID =", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotEqualTo(Integer value) {
			addCriterion("ItemID <>", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidGreaterThan(Integer value) {
			addCriterion("ItemID >", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidGreaterThanOrEqualTo(Integer value) {
			addCriterion("ItemID >=", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidLessThan(Integer value) {
			addCriterion("ItemID <", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidLessThanOrEqualTo(Integer value) {
			addCriterion("ItemID <=", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidIn(List<Integer> values) {
			addCriterion("ItemID in", values, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotIn(List<Integer> values) {
			addCriterion("ItemID not in", values, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidBetween(Integer value1, Integer value2) {
			addCriterion("ItemID between", value1, value2, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotBetween(Integer value1, Integer value2) {
			addCriterion("ItemID not between", value1, value2, "itemid");
			return (Criteria) this;
		}

		public Criteria andNumIsNull() {
			addCriterion("Num is null");
			return (Criteria) this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("Num is not null");
			return (Criteria) this;
		}

		public Criteria andNumEqualTo(Integer value) {
			addCriterion("Num =", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotEqualTo(Integer value) {
			addCriterion("Num <>", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThan(Integer value) {
			addCriterion("Num >", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("Num >=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThan(Integer value) {
			addCriterion("Num <", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThanOrEqualTo(Integer value) {
			addCriterion("Num <=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumIn(List<Integer> values) {
			addCriterion("Num in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotIn(List<Integer> values) {
			addCriterion("Num not in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumBetween(Integer value1, Integer value2) {
			addCriterion("Num between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotBetween(Integer value1, Integer value2) {
			addCriterion("Num not between", value1, value2, "num");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mt_s_equipforge
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mt_s_equipforge
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}