package com.mytribe.db.entity.strategy;

import java.math.BigDecimal;

public class EquipTypeTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.Name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.Star
	 * @mbggenerated
	 */
	private Integer star;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.EquipPart
	 * @mbggenerated
	 */
	private Integer equippart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.AttackTypeID
	 * @mbggenerated
	 */
	private Integer attacktypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.MinAttackSpeed
	 * @mbggenerated
	 */
	private BigDecimal minattackspeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.MaxAttackSpeed
	 * @mbggenerated
	 */
	private BigDecimal maxattackspeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.MinAttack
	 * @mbggenerated
	 */
	private Integer minattack;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.MaxAttack
	 * @mbggenerated
	 */
	private Integer maxattack;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.MinHP
	 * @mbggenerated
	 */
	private Integer minhp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.MaxHP
	 * @mbggenerated
	 */
	private Integer maxhp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.MinMoveSpeed
	 * @mbggenerated
	 */
	private Integer minmovespeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.MaxMoveSpeed
	 * @mbggenerated
	 */
	private Integer maxmovespeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.Icon
	 * @mbggenerated
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.ForgeTime
	 * @mbggenerated
	 */
	private BigDecimal forgetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equiptype.Description
	 * @mbggenerated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.ID
	 * @return  the value of mt_s_equiptype.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.ID
	 * @param id  the value for mt_s_equiptype.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.Name
	 * @return  the value of mt_s_equiptype.Name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.Name
	 * @param name  the value for mt_s_equiptype.Name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.Star
	 * @return  the value of mt_s_equiptype.Star
	 * @mbggenerated
	 */
	public Integer getStar() {
		return star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.Star
	 * @param star  the value for mt_s_equiptype.Star
	 * @mbggenerated
	 */
	public void setStar(Integer star) {
		this.star = star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.EquipPart
	 * @return  the value of mt_s_equiptype.EquipPart
	 * @mbggenerated
	 */
	public Integer getEquippart() {
		return equippart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.EquipPart
	 * @param equippart  the value for mt_s_equiptype.EquipPart
	 * @mbggenerated
	 */
	public void setEquippart(Integer equippart) {
		this.equippart = equippart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.AttackTypeID
	 * @return  the value of mt_s_equiptype.AttackTypeID
	 * @mbggenerated
	 */
	public Integer getAttacktypeid() {
		return attacktypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.AttackTypeID
	 * @param attacktypeid  the value for mt_s_equiptype.AttackTypeID
	 * @mbggenerated
	 */
	public void setAttacktypeid(Integer attacktypeid) {
		this.attacktypeid = attacktypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.MinAttackSpeed
	 * @return  the value of mt_s_equiptype.MinAttackSpeed
	 * @mbggenerated
	 */
	public BigDecimal getMinattackspeed() {
		return minattackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.MinAttackSpeed
	 * @param minattackspeed  the value for mt_s_equiptype.MinAttackSpeed
	 * @mbggenerated
	 */
	public void setMinattackspeed(BigDecimal minattackspeed) {
		this.minattackspeed = minattackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.MaxAttackSpeed
	 * @return  the value of mt_s_equiptype.MaxAttackSpeed
	 * @mbggenerated
	 */
	public BigDecimal getMaxattackspeed() {
		return maxattackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.MaxAttackSpeed
	 * @param maxattackspeed  the value for mt_s_equiptype.MaxAttackSpeed
	 * @mbggenerated
	 */
	public void setMaxattackspeed(BigDecimal maxattackspeed) {
		this.maxattackspeed = maxattackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.MinAttack
	 * @return  the value of mt_s_equiptype.MinAttack
	 * @mbggenerated
	 */
	public Integer getMinattack() {
		return minattack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.MinAttack
	 * @param minattack  the value for mt_s_equiptype.MinAttack
	 * @mbggenerated
	 */
	public void setMinattack(Integer minattack) {
		this.minattack = minattack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.MaxAttack
	 * @return  the value of mt_s_equiptype.MaxAttack
	 * @mbggenerated
	 */
	public Integer getMaxattack() {
		return maxattack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.MaxAttack
	 * @param maxattack  the value for mt_s_equiptype.MaxAttack
	 * @mbggenerated
	 */
	public void setMaxattack(Integer maxattack) {
		this.maxattack = maxattack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.MinHP
	 * @return  the value of mt_s_equiptype.MinHP
	 * @mbggenerated
	 */
	public Integer getMinhp() {
		return minhp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.MinHP
	 * @param minhp  the value for mt_s_equiptype.MinHP
	 * @mbggenerated
	 */
	public void setMinhp(Integer minhp) {
		this.minhp = minhp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.MaxHP
	 * @return  the value of mt_s_equiptype.MaxHP
	 * @mbggenerated
	 */
	public Integer getMaxhp() {
		return maxhp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.MaxHP
	 * @param maxhp  the value for mt_s_equiptype.MaxHP
	 * @mbggenerated
	 */
	public void setMaxhp(Integer maxhp) {
		this.maxhp = maxhp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.MinMoveSpeed
	 * @return  the value of mt_s_equiptype.MinMoveSpeed
	 * @mbggenerated
	 */
	public Integer getMinmovespeed() {
		return minmovespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.MinMoveSpeed
	 * @param minmovespeed  the value for mt_s_equiptype.MinMoveSpeed
	 * @mbggenerated
	 */
	public void setMinmovespeed(Integer minmovespeed) {
		this.minmovespeed = minmovespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.MaxMoveSpeed
	 * @return  the value of mt_s_equiptype.MaxMoveSpeed
	 * @mbggenerated
	 */
	public Integer getMaxmovespeed() {
		return maxmovespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.MaxMoveSpeed
	 * @param maxmovespeed  the value for mt_s_equiptype.MaxMoveSpeed
	 * @mbggenerated
	 */
	public void setMaxmovespeed(Integer maxmovespeed) {
		this.maxmovespeed = maxmovespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.Icon
	 * @return  the value of mt_s_equiptype.Icon
	 * @mbggenerated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.Icon
	 * @param icon  the value for mt_s_equiptype.Icon
	 * @mbggenerated
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.ForgeTime
	 * @return  the value of mt_s_equiptype.ForgeTime
	 * @mbggenerated
	 */
	public BigDecimal getForgetime() {
		return forgetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.ForgeTime
	 * @param forgetime  the value for mt_s_equiptype.ForgeTime
	 * @mbggenerated
	 */
	public void setForgetime(BigDecimal forgetime) {
		this.forgetime = forgetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equiptype.Description
	 * @return  the value of mt_s_equiptype.Description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equiptype.Description
	 * @param description  the value for mt_s_equiptype.Description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}