package com.mytribe.db.entity.strategy;

public class EquipForgeTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equipforge.EquipID
	 * @mbggenerated
	 */
	private Integer equipid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equipforge.ItemID
	 * @mbggenerated
	 */
	private Integer itemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_equipforge.Num
	 * @mbggenerated
	 */
	private Integer num;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equipforge.EquipID
	 * @return  the value of mt_s_equipforge.EquipID
	 * @mbggenerated
	 */
	public Integer getEquipid() {
		return equipid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equipforge.EquipID
	 * @param equipid  the value for mt_s_equipforge.EquipID
	 * @mbggenerated
	 */
	public void setEquipid(Integer equipid) {
		this.equipid = equipid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equipforge.ItemID
	 * @return  the value of mt_s_equipforge.ItemID
	 * @mbggenerated
	 */
	public Integer getItemid() {
		return itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equipforge.ItemID
	 * @param itemid  the value for mt_s_equipforge.ItemID
	 * @mbggenerated
	 */
	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_equipforge.Num
	 * @return  the value of mt_s_equipforge.Num
	 * @mbggenerated
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_equipforge.Num
	 * @param num  the value for mt_s_equipforge.Num
	 * @mbggenerated
	 */
	public void setNum(Integer num) {
		this.num = num;
	}
}