package com.mytribe.db.entity.strategy;

public class GradeExpTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_grade_exp.Grade
	 * @mbggenerated
	 */
	private Integer grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_grade_exp.NeedExp
	 * @mbggenerated
	 */
	private Integer needexp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_grade_exp.Grade
	 * @return  the value of mt_s_grade_exp.Grade
	 * @mbggenerated
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_grade_exp.Grade
	 * @param grade  the value for mt_s_grade_exp.Grade
	 * @mbggenerated
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_grade_exp.NeedExp
	 * @return  the value of mt_s_grade_exp.NeedExp
	 * @mbggenerated
	 */
	public Integer getNeedexp() {
		return needexp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_grade_exp.NeedExp
	 * @param needexp  the value for mt_s_grade_exp.NeedExp
	 * @mbggenerated
	 */
	public void setNeedexp(Integer needexp) {
		this.needexp = needexp;
	}
}