package com.mytribe.db.entity.strategy;

public class ItemTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_item.ItemID
	 * @mbggenerated
	 */
	private Integer itemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_item.Name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_item.Star
	 * @mbggenerated
	 */
	private Integer star;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_item.Icon
	 * @mbggenerated
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_item.Description
	 * @mbggenerated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_item.ItemID
	 * @return  the value of mt_s_item.ItemID
	 * @mbggenerated
	 */
	public Integer getItemid() {
		return itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_item.ItemID
	 * @param itemid  the value for mt_s_item.ItemID
	 * @mbggenerated
	 */
	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_item.Name
	 * @return  the value of mt_s_item.Name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_item.Name
	 * @param name  the value for mt_s_item.Name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_item.Star
	 * @return  the value of mt_s_item.Star
	 * @mbggenerated
	 */
	public Integer getStar() {
		return star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_item.Star
	 * @param star  the value for mt_s_item.Star
	 * @mbggenerated
	 */
	public void setStar(Integer star) {
		this.star = star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_item.Icon
	 * @return  the value of mt_s_item.Icon
	 * @mbggenerated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_item.Icon
	 * @param icon  the value for mt_s_item.Icon
	 * @mbggenerated
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_item.Description
	 * @return  the value of mt_s_item.Description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_item.Description
	 * @param description  the value for mt_s_item.Description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}