package com.mytribe.db.entity.strategy;

import java.math.BigDecimal;

public class MainRoleBaseInfoTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_mainrolebaseinfo.MainRoleID
	 * @mbggenerated
	 */
	private Integer mainroleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_mainrolebaseinfo.Name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_mainrolebaseinfo.AttackSpeed
	 * @mbggenerated
	 */
	private BigDecimal attackspeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_mainrolebaseinfo.Attack
	 * @mbggenerated
	 */
	private Integer attack;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_mainrolebaseinfo.HP
	 * @mbggenerated
	 */
	private Integer hp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_mainrolebaseinfo.MoveSpeed
	 * @mbggenerated
	 */
	private Integer movespeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_mainrolebaseinfo.MaxGrade
	 * @mbggenerated
	 */
	private Integer maxgrade;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_mainrolebaseinfo.MainRoleID
	 * @return  the value of mt_s_mainrolebaseinfo.MainRoleID
	 * @mbggenerated
	 */
	public Integer getMainroleid() {
		return mainroleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_mainrolebaseinfo.MainRoleID
	 * @param mainroleid  the value for mt_s_mainrolebaseinfo.MainRoleID
	 * @mbggenerated
	 */
	public void setMainroleid(Integer mainroleid) {
		this.mainroleid = mainroleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_mainrolebaseinfo.Name
	 * @return  the value of mt_s_mainrolebaseinfo.Name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_mainrolebaseinfo.Name
	 * @param name  the value for mt_s_mainrolebaseinfo.Name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_mainrolebaseinfo.AttackSpeed
	 * @return  the value of mt_s_mainrolebaseinfo.AttackSpeed
	 * @mbggenerated
	 */
	public BigDecimal getAttackspeed() {
		return attackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_mainrolebaseinfo.AttackSpeed
	 * @param attackspeed  the value for mt_s_mainrolebaseinfo.AttackSpeed
	 * @mbggenerated
	 */
	public void setAttackspeed(BigDecimal attackspeed) {
		this.attackspeed = attackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_mainrolebaseinfo.Attack
	 * @return  the value of mt_s_mainrolebaseinfo.Attack
	 * @mbggenerated
	 */
	public Integer getAttack() {
		return attack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_mainrolebaseinfo.Attack
	 * @param attack  the value for mt_s_mainrolebaseinfo.Attack
	 * @mbggenerated
	 */
	public void setAttack(Integer attack) {
		this.attack = attack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_mainrolebaseinfo.HP
	 * @return  the value of mt_s_mainrolebaseinfo.HP
	 * @mbggenerated
	 */
	public Integer getHp() {
		return hp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_mainrolebaseinfo.HP
	 * @param hp  the value for mt_s_mainrolebaseinfo.HP
	 * @mbggenerated
	 */
	public void setHp(Integer hp) {
		this.hp = hp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_mainrolebaseinfo.MoveSpeed
	 * @return  the value of mt_s_mainrolebaseinfo.MoveSpeed
	 * @mbggenerated
	 */
	public Integer getMovespeed() {
		return movespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_mainrolebaseinfo.MoveSpeed
	 * @param movespeed  the value for mt_s_mainrolebaseinfo.MoveSpeed
	 * @mbggenerated
	 */
	public void setMovespeed(Integer movespeed) {
		this.movespeed = movespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_mainrolebaseinfo.MaxGrade
	 * @return  the value of mt_s_mainrolebaseinfo.MaxGrade
	 * @mbggenerated
	 */
	public Integer getMaxgrade() {
		return maxgrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_mainrolebaseinfo.MaxGrade
	 * @param maxgrade  the value for mt_s_mainrolebaseinfo.MaxGrade
	 * @mbggenerated
	 */
	public void setMaxgrade(Integer maxgrade) {
		this.maxgrade = maxgrade;
	}
}