package com.mytribe.db.entity.strategy;

public class PlayerArmyEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_playerarmy.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_playerarmy.PlayerID
	 * @mbggenerated
	 */
	private Integer playerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_playerarmy.ArmyID
	 * @mbggenerated
	 */
	private Integer armyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_playerarmy.BuildingID
	 * @mbggenerated
	 */
	private Integer buildingid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_playerarmy.SoldierTypeID
	 * @mbggenerated
	 */
	private Integer soldiertypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_playerarmy.SoldierNum
	 * @mbggenerated
	 */
	private Integer soldiernum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_playerarmy.id
	 * @return  the value of mt_u_playerarmy.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_playerarmy.id
	 * @param id  the value for mt_u_playerarmy.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_playerarmy.PlayerID
	 * @return  the value of mt_u_playerarmy.PlayerID
	 * @mbggenerated
	 */
	public Integer getPlayerid() {
		return playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_playerarmy.PlayerID
	 * @param playerid  the value for mt_u_playerarmy.PlayerID
	 * @mbggenerated
	 */
	public void setPlayerid(Integer playerid) {
		this.playerid = playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_playerarmy.ArmyID
	 * @return  the value of mt_u_playerarmy.ArmyID
	 * @mbggenerated
	 */
	public Integer getArmyid() {
		return armyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_playerarmy.ArmyID
	 * @param armyid  the value for mt_u_playerarmy.ArmyID
	 * @mbggenerated
	 */
	public void setArmyid(Integer armyid) {
		this.armyid = armyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_playerarmy.BuildingID
	 * @return  the value of mt_u_playerarmy.BuildingID
	 * @mbggenerated
	 */
	public Integer getBuildingid() {
		return buildingid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_playerarmy.BuildingID
	 * @param buildingid  the value for mt_u_playerarmy.BuildingID
	 * @mbggenerated
	 */
	public void setBuildingid(Integer buildingid) {
		this.buildingid = buildingid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_playerarmy.SoldierTypeID
	 * @return  the value of mt_u_playerarmy.SoldierTypeID
	 * @mbggenerated
	 */
	public Integer getSoldiertypeid() {
		return soldiertypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_playerarmy.SoldierTypeID
	 * @param soldiertypeid  the value for mt_u_playerarmy.SoldierTypeID
	 * @mbggenerated
	 */
	public void setSoldiertypeid(Integer soldiertypeid) {
		this.soldiertypeid = soldiertypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_playerarmy.SoldierNum
	 * @return  the value of mt_u_playerarmy.SoldierNum
	 * @mbggenerated
	 */
	public Integer getSoldiernum() {
		return soldiernum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_playerarmy.SoldierNum
	 * @param soldiernum  the value for mt_u_playerarmy.SoldierNum
	 * @mbggenerated
	 */
	public void setSoldiernum(Integer soldiernum) {
		this.soldiernum = soldiernum;
	}
}