package com.mytribe.db.entity.strategy;

public class PlayerSoldierGradeEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_soldiergrade.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_soldiergrade.PlayerID
	 * @mbggenerated
	 */
	private Integer playerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_soldiergrade.SoldierTypeID
	 * @mbggenerated
	 */
	private Integer soldiertypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_soldiergrade.Grade
	 * @mbggenerated
	 */
	private Integer grade;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_soldiergrade.id
	 * @return  the value of mt_u_player_soldiergrade.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_soldiergrade.id
	 * @param id  the value for mt_u_player_soldiergrade.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_soldiergrade.PlayerID
	 * @return  the value of mt_u_player_soldiergrade.PlayerID
	 * @mbggenerated
	 */
	public Integer getPlayerid() {
		return playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_soldiergrade.PlayerID
	 * @param playerid  the value for mt_u_player_soldiergrade.PlayerID
	 * @mbggenerated
	 */
	public void setPlayerid(Integer playerid) {
		this.playerid = playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_soldiergrade.SoldierTypeID
	 * @return  the value of mt_u_player_soldiergrade.SoldierTypeID
	 * @mbggenerated
	 */
	public Integer getSoldiertypeid() {
		return soldiertypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_soldiergrade.SoldierTypeID
	 * @param soldiertypeid  the value for mt_u_player_soldiergrade.SoldierTypeID
	 * @mbggenerated
	 */
	public void setSoldiertypeid(Integer soldiertypeid) {
		this.soldiertypeid = soldiertypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_soldiergrade.Grade
	 * @return  the value of mt_u_player_soldiergrade.Grade
	 * @mbggenerated
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_soldiergrade.Grade
	 * @param grade  the value for mt_u_player_soldiergrade.Grade
	 * @mbggenerated
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}
}