package com.mytribe.db.entity.strategy;

import java.math.BigDecimal;

public class PlayerEquipEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_equip.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_equip.PlayerID
	 * @mbggenerated
	 */
	private Integer playerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_equip.EquipID
	 * @mbggenerated
	 */
	private Integer equipid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_equip.SkillID
	 * @mbggenerated
	 */
	private Integer skillid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_equip.AttackSpeed
	 * @mbggenerated
	 */
	private BigDecimal attackspeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_equip.Attack
	 * @mbggenerated
	 */
	private Integer attack;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_equip.HP
	 * @mbggenerated
	 */
	private Integer hp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_equip.MoveSpeed
	 * @mbggenerated
	 */
	private Integer movespeed;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_equip.id
	 * @return  the value of mt_u_player_equip.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_equip.id
	 * @param id  the value for mt_u_player_equip.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_equip.PlayerID
	 * @return  the value of mt_u_player_equip.PlayerID
	 * @mbggenerated
	 */
	public Integer getPlayerid() {
		return playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_equip.PlayerID
	 * @param playerid  the value for mt_u_player_equip.PlayerID
	 * @mbggenerated
	 */
	public void setPlayerid(Integer playerid) {
		this.playerid = playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_equip.EquipID
	 * @return  the value of mt_u_player_equip.EquipID
	 * @mbggenerated
	 */
	public Integer getEquipid() {
		return equipid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_equip.EquipID
	 * @param equipid  the value for mt_u_player_equip.EquipID
	 * @mbggenerated
	 */
	public void setEquipid(Integer equipid) {
		this.equipid = equipid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_equip.SkillID
	 * @return  the value of mt_u_player_equip.SkillID
	 * @mbggenerated
	 */
	public Integer getSkillid() {
		return skillid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_equip.SkillID
	 * @param skillid  the value for mt_u_player_equip.SkillID
	 * @mbggenerated
	 */
	public void setSkillid(Integer skillid) {
		this.skillid = skillid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_equip.AttackSpeed
	 * @return  the value of mt_u_player_equip.AttackSpeed
	 * @mbggenerated
	 */
	public BigDecimal getAttackspeed() {
		return attackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_equip.AttackSpeed
	 * @param attackspeed  the value for mt_u_player_equip.AttackSpeed
	 * @mbggenerated
	 */
	public void setAttackspeed(BigDecimal attackspeed) {
		this.attackspeed = attackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_equip.Attack
	 * @return  the value of mt_u_player_equip.Attack
	 * @mbggenerated
	 */
	public Integer getAttack() {
		return attack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_equip.Attack
	 * @param attack  the value for mt_u_player_equip.Attack
	 * @mbggenerated
	 */
	public void setAttack(Integer attack) {
		this.attack = attack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_equip.HP
	 * @return  the value of mt_u_player_equip.HP
	 * @mbggenerated
	 */
	public Integer getHp() {
		return hp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_equip.HP
	 * @param hp  the value for mt_u_player_equip.HP
	 * @mbggenerated
	 */
	public void setHp(Integer hp) {
		this.hp = hp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_equip.MoveSpeed
	 * @return  the value of mt_u_player_equip.MoveSpeed
	 * @mbggenerated
	 */
	public Integer getMovespeed() {
		return movespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_equip.MoveSpeed
	 * @param movespeed  the value for mt_u_player_equip.MoveSpeed
	 * @mbggenerated
	 */
	public void setMovespeed(Integer movespeed) {
		this.movespeed = movespeed;
	}
}