package com.mytribe.db.entity.strategy;

import java.util.ArrayList;
import java.util.List;

public class PlayerItemEntityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public PlayerItemEntityExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPlayeridIsNull() {
			addCriterion("PlayerID is null");
			return (Criteria) this;
		}

		public Criteria andPlayeridIsNotNull() {
			addCriterion("PlayerID is not null");
			return (Criteria) this;
		}

		public Criteria andPlayeridEqualTo(Integer value) {
			addCriterion("PlayerID =", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridNotEqualTo(Integer value) {
			addCriterion("PlayerID <>", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridGreaterThan(Integer value) {
			addCriterion("PlayerID >", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridGreaterThanOrEqualTo(Integer value) {
			addCriterion("PlayerID >=", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridLessThan(Integer value) {
			addCriterion("PlayerID <", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridLessThanOrEqualTo(Integer value) {
			addCriterion("PlayerID <=", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridIn(List<Integer> values) {
			addCriterion("PlayerID in", values, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridNotIn(List<Integer> values) {
			addCriterion("PlayerID not in", values, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridBetween(Integer value1, Integer value2) {
			addCriterion("PlayerID between", value1, value2, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridNotBetween(Integer value1, Integer value2) {
			addCriterion("PlayerID not between", value1, value2, "playerid");
			return (Criteria) this;
		}

		public Criteria andItemidIsNull() {
			addCriterion("ItemID is null");
			return (Criteria) this;
		}

		public Criteria andItemidIsNotNull() {
			addCriterion("ItemID is not null");
			return (Criteria) this;
		}

		public Criteria andItemidEqualTo(Integer value) {
			addCriterion("ItemID =", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotEqualTo(Integer value) {
			addCriterion("ItemID <>", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidGreaterThan(Integer value) {
			addCriterion("ItemID >", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidGreaterThanOrEqualTo(Integer value) {
			addCriterion("ItemID >=", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidLessThan(Integer value) {
			addCriterion("ItemID <", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidLessThanOrEqualTo(Integer value) {
			addCriterion("ItemID <=", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidIn(List<Integer> values) {
			addCriterion("ItemID in", values, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotIn(List<Integer> values) {
			addCriterion("ItemID not in", values, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidBetween(Integer value1, Integer value2) {
			addCriterion("ItemID between", value1, value2, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotBetween(Integer value1, Integer value2) {
			addCriterion("ItemID not between", value1, value2, "itemid");
			return (Criteria) this;
		}

		public Criteria andNumIsNull() {
			addCriterion("Num is null");
			return (Criteria) this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("Num is not null");
			return (Criteria) this;
		}

		public Criteria andNumEqualTo(Integer value) {
			addCriterion("Num =", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotEqualTo(Integer value) {
			addCriterion("Num <>", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThan(Integer value) {
			addCriterion("Num >", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("Num >=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThan(Integer value) {
			addCriterion("Num <", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThanOrEqualTo(Integer value) {
			addCriterion("Num <=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumIn(List<Integer> values) {
			addCriterion("Num in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotIn(List<Integer> values) {
			addCriterion("Num not in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumBetween(Integer value1, Integer value2) {
			addCriterion("Num between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotBetween(Integer value1, Integer value2) {
			addCriterion("Num not between", value1, value2, "num");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mt_u_player_item
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}