package com.mytribe.db.entity.strategy;

public class PlayerItemEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_item.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_item.PlayerID
	 * @mbggenerated
	 */
	private Integer playerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_item.ItemID
	 * @mbggenerated
	 */
	private Integer itemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_item.Num
	 * @mbggenerated
	 */
	private Integer num;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_item.id
	 * @return  the value of mt_u_player_item.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_item.id
	 * @param id  the value for mt_u_player_item.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_item.PlayerID
	 * @return  the value of mt_u_player_item.PlayerID
	 * @mbggenerated
	 */
	public Integer getPlayerid() {
		return playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_item.PlayerID
	 * @param playerid  the value for mt_u_player_item.PlayerID
	 * @mbggenerated
	 */
	public void setPlayerid(Integer playerid) {
		this.playerid = playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_item.ItemID
	 * @return  the value of mt_u_player_item.ItemID
	 * @mbggenerated
	 */
	public Integer getItemid() {
		return itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_item.ItemID
	 * @param itemid  the value for mt_u_player_item.ItemID
	 * @mbggenerated
	 */
	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_item.Num
	 * @return  the value of mt_u_player_item.Num
	 * @mbggenerated
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_item.Num
	 * @param num  the value for mt_u_player_item.Num
	 * @mbggenerated
	 */
	public void setNum(Integer num) {
		this.num = num;
	}
}