package com.mytribe.db.entity.strategy;

public class PlayerBuildingEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_building.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_building.PlayerID
	 * @mbggenerated
	 */
	private Integer playerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_building.BuildingID
	 * @mbggenerated
	 */
	private Integer buildingid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_building.BuildingTypeID
	 * @mbggenerated
	 */
	private Integer buildingtypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_building.Grade
	 * @mbggenerated
	 */
	private Integer grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_building.CurrentColumn
	 * @mbggenerated
	 */
	private Integer currentcolumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_building.PositionX
	 * @mbggenerated
	 */
	private Integer positionx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_player_building.PositionY
	 * @mbggenerated
	 */
	private Integer positiony;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_building.id
	 * @return  the value of mt_u_player_building.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_building.id
	 * @param id  the value for mt_u_player_building.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_building.PlayerID
	 * @return  the value of mt_u_player_building.PlayerID
	 * @mbggenerated
	 */
	public Integer getPlayerid() {
		return playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_building.PlayerID
	 * @param playerid  the value for mt_u_player_building.PlayerID
	 * @mbggenerated
	 */
	public void setPlayerid(Integer playerid) {
		this.playerid = playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_building.BuildingID
	 * @return  the value of mt_u_player_building.BuildingID
	 * @mbggenerated
	 */
	public Integer getBuildingid() {
		return buildingid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_building.BuildingID
	 * @param buildingid  the value for mt_u_player_building.BuildingID
	 * @mbggenerated
	 */
	public void setBuildingid(Integer buildingid) {
		this.buildingid = buildingid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_building.BuildingTypeID
	 * @return  the value of mt_u_player_building.BuildingTypeID
	 * @mbggenerated
	 */
	public Integer getBuildingtypeid() {
		return buildingtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_building.BuildingTypeID
	 * @param buildingtypeid  the value for mt_u_player_building.BuildingTypeID
	 * @mbggenerated
	 */
	public void setBuildingtypeid(Integer buildingtypeid) {
		this.buildingtypeid = buildingtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_building.Grade
	 * @return  the value of mt_u_player_building.Grade
	 * @mbggenerated
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_building.Grade
	 * @param grade  the value for mt_u_player_building.Grade
	 * @mbggenerated
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_building.CurrentColumn
	 * @return  the value of mt_u_player_building.CurrentColumn
	 * @mbggenerated
	 */
	public Integer getCurrentcolumn() {
		return currentcolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_building.CurrentColumn
	 * @param currentcolumn  the value for mt_u_player_building.CurrentColumn
	 * @mbggenerated
	 */
	public void setCurrentcolumn(Integer currentcolumn) {
		this.currentcolumn = currentcolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_building.PositionX
	 * @return  the value of mt_u_player_building.PositionX
	 * @mbggenerated
	 */
	public Integer getPositionx() {
		return positionx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_building.PositionX
	 * @param positionx  the value for mt_u_player_building.PositionX
	 * @mbggenerated
	 */
	public void setPositionx(Integer positionx) {
		this.positionx = positionx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_player_building.PositionY
	 * @return  the value of mt_u_player_building.PositionY
	 * @mbggenerated
	 */
	public Integer getPositiony() {
		return positiony;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_player_building.PositionY
	 * @param positiony  the value for mt_u_player_building.PositionY
	 * @mbggenerated
	 */
	public void setPositiony(Integer positiony) {
		this.positiony = positiony;
	}
}