package com.mytribe.db.entity.strategy;

import java.math.BigDecimal;

public class SkillTypeTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_skilltype.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_skilltype.Star
	 * @mbggenerated
	 */
	private Integer star;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_skilltype.Name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_skilltype.AttackTypeID
	 * @mbggenerated
	 */
	private Integer attacktypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_skilltype.SkillEffectValue
	 * @mbggenerated
	 */
	private BigDecimal skilleffectvalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_skilltype.SpecialEffect
	 * @mbggenerated
	 */
	private String specialeffect;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_skilltype.Icon
	 * @mbggenerated
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_skilltype.CD
	 * @mbggenerated
	 */
	private BigDecimal cd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_skilltype.Range
	 * @mbggenerated
	 */
	private BigDecimal range;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_skilltype.Description
	 * @mbggenerated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_skilltype.ID
	 * @return  the value of mt_s_skilltype.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_skilltype.ID
	 * @param id  the value for mt_s_skilltype.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_skilltype.Star
	 * @return  the value of mt_s_skilltype.Star
	 * @mbggenerated
	 */
	public Integer getStar() {
		return star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_skilltype.Star
	 * @param star  the value for mt_s_skilltype.Star
	 * @mbggenerated
	 */
	public void setStar(Integer star) {
		this.star = star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_skilltype.Name
	 * @return  the value of mt_s_skilltype.Name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_skilltype.Name
	 * @param name  the value for mt_s_skilltype.Name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_skilltype.AttackTypeID
	 * @return  the value of mt_s_skilltype.AttackTypeID
	 * @mbggenerated
	 */
	public Integer getAttacktypeid() {
		return attacktypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_skilltype.AttackTypeID
	 * @param attacktypeid  the value for mt_s_skilltype.AttackTypeID
	 * @mbggenerated
	 */
	public void setAttacktypeid(Integer attacktypeid) {
		this.attacktypeid = attacktypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_skilltype.SkillEffectValue
	 * @return  the value of mt_s_skilltype.SkillEffectValue
	 * @mbggenerated
	 */
	public BigDecimal getSkilleffectvalue() {
		return skilleffectvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_skilltype.SkillEffectValue
	 * @param skilleffectvalue  the value for mt_s_skilltype.SkillEffectValue
	 * @mbggenerated
	 */
	public void setSkilleffectvalue(BigDecimal skilleffectvalue) {
		this.skilleffectvalue = skilleffectvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_skilltype.SpecialEffect
	 * @return  the value of mt_s_skilltype.SpecialEffect
	 * @mbggenerated
	 */
	public String getSpecialeffect() {
		return specialeffect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_skilltype.SpecialEffect
	 * @param specialeffect  the value for mt_s_skilltype.SpecialEffect
	 * @mbggenerated
	 */
	public void setSpecialeffect(String specialeffect) {
		this.specialeffect = specialeffect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_skilltype.Icon
	 * @return  the value of mt_s_skilltype.Icon
	 * @mbggenerated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_skilltype.Icon
	 * @param icon  the value for mt_s_skilltype.Icon
	 * @mbggenerated
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_skilltype.CD
	 * @return  the value of mt_s_skilltype.CD
	 * @mbggenerated
	 */
	public BigDecimal getCd() {
		return cd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_skilltype.CD
	 * @param cd  the value for mt_s_skilltype.CD
	 * @mbggenerated
	 */
	public void setCd(BigDecimal cd) {
		this.cd = cd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_skilltype.Range
	 * @return  the value of mt_s_skilltype.Range
	 * @mbggenerated
	 */
	public BigDecimal getRange() {
		return range;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_skilltype.Range
	 * @param range  the value for mt_s_skilltype.Range
	 * @mbggenerated
	 */
	public void setRange(BigDecimal range) {
		this.range = range;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_skilltype.Description
	 * @return  the value of mt_s_skilltype.Description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_skilltype.Description
	 * @param description  the value for mt_s_skilltype.Description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}