package com.mytribe.db.entity.strategy;

import java.math.BigDecimal;

public class SoldierTypeTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiertype.SoldierTypeID
	 * @mbggenerated
	 */
	private Integer soldiertypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiertype.Name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiertype.AttackTypeID
	 * @mbggenerated
	 */
	private Integer attacktypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiertype.Range
	 * @mbggenerated
	 */
	private BigDecimal range;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiertype.ConsumePos
	 * @mbggenerated
	 */
	private Integer consumepos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiertype.MonitorRange
	 * @mbggenerated
	 */
	private BigDecimal monitorrange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiertype.Model
	 * @mbggenerated
	 */
	private String model;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiertype.Icon
	 * @mbggenerated
	 */
	private String icon;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiertype.SoldierTypeID
	 * @return  the value of mt_s_soldiertype.SoldierTypeID
	 * @mbggenerated
	 */
	public Integer getSoldiertypeid() {
		return soldiertypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiertype.SoldierTypeID
	 * @param soldiertypeid  the value for mt_s_soldiertype.SoldierTypeID
	 * @mbggenerated
	 */
	public void setSoldiertypeid(Integer soldiertypeid) {
		this.soldiertypeid = soldiertypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiertype.Name
	 * @return  the value of mt_s_soldiertype.Name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiertype.Name
	 * @param name  the value for mt_s_soldiertype.Name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiertype.AttackTypeID
	 * @return  the value of mt_s_soldiertype.AttackTypeID
	 * @mbggenerated
	 */
	public Integer getAttacktypeid() {
		return attacktypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiertype.AttackTypeID
	 * @param attacktypeid  the value for mt_s_soldiertype.AttackTypeID
	 * @mbggenerated
	 */
	public void setAttacktypeid(Integer attacktypeid) {
		this.attacktypeid = attacktypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiertype.Range
	 * @return  the value of mt_s_soldiertype.Range
	 * @mbggenerated
	 */
	public BigDecimal getRange() {
		return range;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiertype.Range
	 * @param range  the value for mt_s_soldiertype.Range
	 * @mbggenerated
	 */
	public void setRange(BigDecimal range) {
		this.range = range;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiertype.ConsumePos
	 * @return  the value of mt_s_soldiertype.ConsumePos
	 * @mbggenerated
	 */
	public Integer getConsumepos() {
		return consumepos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiertype.ConsumePos
	 * @param consumepos  the value for mt_s_soldiertype.ConsumePos
	 * @mbggenerated
	 */
	public void setConsumepos(Integer consumepos) {
		this.consumepos = consumepos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiertype.MonitorRange
	 * @return  the value of mt_s_soldiertype.MonitorRange
	 * @mbggenerated
	 */
	public BigDecimal getMonitorrange() {
		return monitorrange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiertype.MonitorRange
	 * @param monitorrange  the value for mt_s_soldiertype.MonitorRange
	 * @mbggenerated
	 */
	public void setMonitorrange(BigDecimal monitorrange) {
		this.monitorrange = monitorrange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiertype.Model
	 * @return  the value of mt_s_soldiertype.Model
	 * @mbggenerated
	 */
	public String getModel() {
		return model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiertype.Model
	 * @param model  the value for mt_s_soldiertype.Model
	 * @mbggenerated
	 */
	public void setModel(String model) {
		this.model = model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiertype.Icon
	 * @return  the value of mt_s_soldiertype.Icon
	 * @mbggenerated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiertype.Icon
	 * @param icon  the value for mt_s_soldiertype.Icon
	 * @mbggenerated
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}
}