package com.mytribe.db.entity.strategy;

import java.math.BigDecimal;

public class SoldierGradeInfoTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiergradeinfo.SoldierTypeID
	 * @mbggenerated
	 */
	private Integer soldiertypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiergradeinfo.Grade
	 * @mbggenerated
	 */
	private Integer grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiergradeinfo.Attack
	 * @mbggenerated
	 */
	private Integer attack;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiergradeinfo.AttackSpeed
	 * @mbggenerated
	 */
	private BigDecimal attackspeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiergradeinfo.Blood
	 * @mbggenerated
	 */
	private Integer blood;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiergradeinfo.MoveSpeed
	 * @mbggenerated
	 */
	private Integer movespeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiergradeinfo.UpgradeCoinCost
	 * @mbggenerated
	 */
	private Integer upgradecoincost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiergradeinfo.UpgradeTimeCost
	 * @mbggenerated
	 */
	private Integer upgradetimecost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiergradeinfo.ProduceCoinCost
	 * @mbggenerated
	 */
	private Integer producecoincost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_soldiergradeinfo.ProduceTimeCost
	 * @mbggenerated
	 */
	private Integer producetimecost;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiergradeinfo.SoldierTypeID
	 * @return  the value of mt_s_soldiergradeinfo.SoldierTypeID
	 * @mbggenerated
	 */
	public Integer getSoldiertypeid() {
		return soldiertypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiergradeinfo.SoldierTypeID
	 * @param soldiertypeid  the value for mt_s_soldiergradeinfo.SoldierTypeID
	 * @mbggenerated
	 */
	public void setSoldiertypeid(Integer soldiertypeid) {
		this.soldiertypeid = soldiertypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiergradeinfo.Grade
	 * @return  the value of mt_s_soldiergradeinfo.Grade
	 * @mbggenerated
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiergradeinfo.Grade
	 * @param grade  the value for mt_s_soldiergradeinfo.Grade
	 * @mbggenerated
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiergradeinfo.Attack
	 * @return  the value of mt_s_soldiergradeinfo.Attack
	 * @mbggenerated
	 */
	public Integer getAttack() {
		return attack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiergradeinfo.Attack
	 * @param attack  the value for mt_s_soldiergradeinfo.Attack
	 * @mbggenerated
	 */
	public void setAttack(Integer attack) {
		this.attack = attack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiergradeinfo.AttackSpeed
	 * @return  the value of mt_s_soldiergradeinfo.AttackSpeed
	 * @mbggenerated
	 */
	public BigDecimal getAttackspeed() {
		return attackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiergradeinfo.AttackSpeed
	 * @param attackspeed  the value for mt_s_soldiergradeinfo.AttackSpeed
	 * @mbggenerated
	 */
	public void setAttackspeed(BigDecimal attackspeed) {
		this.attackspeed = attackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiergradeinfo.Blood
	 * @return  the value of mt_s_soldiergradeinfo.Blood
	 * @mbggenerated
	 */
	public Integer getBlood() {
		return blood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiergradeinfo.Blood
	 * @param blood  the value for mt_s_soldiergradeinfo.Blood
	 * @mbggenerated
	 */
	public void setBlood(Integer blood) {
		this.blood = blood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiergradeinfo.MoveSpeed
	 * @return  the value of mt_s_soldiergradeinfo.MoveSpeed
	 * @mbggenerated
	 */
	public Integer getMovespeed() {
		return movespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiergradeinfo.MoveSpeed
	 * @param movespeed  the value for mt_s_soldiergradeinfo.MoveSpeed
	 * @mbggenerated
	 */
	public void setMovespeed(Integer movespeed) {
		this.movespeed = movespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiergradeinfo.UpgradeCoinCost
	 * @return  the value of mt_s_soldiergradeinfo.UpgradeCoinCost
	 * @mbggenerated
	 */
	public Integer getUpgradecoincost() {
		return upgradecoincost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiergradeinfo.UpgradeCoinCost
	 * @param upgradecoincost  the value for mt_s_soldiergradeinfo.UpgradeCoinCost
	 * @mbggenerated
	 */
	public void setUpgradecoincost(Integer upgradecoincost) {
		this.upgradecoincost = upgradecoincost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiergradeinfo.UpgradeTimeCost
	 * @return  the value of mt_s_soldiergradeinfo.UpgradeTimeCost
	 * @mbggenerated
	 */
	public Integer getUpgradetimecost() {
		return upgradetimecost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiergradeinfo.UpgradeTimeCost
	 * @param upgradetimecost  the value for mt_s_soldiergradeinfo.UpgradeTimeCost
	 * @mbggenerated
	 */
	public void setUpgradetimecost(Integer upgradetimecost) {
		this.upgradetimecost = upgradetimecost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiergradeinfo.ProduceCoinCost
	 * @return  the value of mt_s_soldiergradeinfo.ProduceCoinCost
	 * @mbggenerated
	 */
	public Integer getProducecoincost() {
		return producecoincost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiergradeinfo.ProduceCoinCost
	 * @param producecoincost  the value for mt_s_soldiergradeinfo.ProduceCoinCost
	 * @mbggenerated
	 */
	public void setProducecoincost(Integer producecoincost) {
		this.producecoincost = producecoincost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_soldiergradeinfo.ProduceTimeCost
	 * @return  the value of mt_s_soldiergradeinfo.ProduceTimeCost
	 * @mbggenerated
	 */
	public Integer getProducetimecost() {
		return producetimecost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_soldiergradeinfo.ProduceTimeCost
	 * @param producetimecost  the value for mt_s_soldiergradeinfo.ProduceTimeCost
	 * @mbggenerated
	 */
	public void setProducetimecost(Integer producetimecost) {
		this.producetimecost = producetimecost;
	}
}