package com.mytribe.db.entity.strategy;

import java.math.BigDecimal;

public class SylphbeastTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.Name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.Star
	 * @mbggenerated
	 */
	private Integer star;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.RadarUnlockGrade
	 * @mbggenerated
	 */
	private Integer radarunlockgrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.SylphBeastStoreGrade
	 * @mbggenerated
	 */
	private Integer sylphbeaststoregrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.AttackTypeID
	 * @mbggenerated
	 */
	private Integer attacktypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.MinAttackSpeed
	 * @mbggenerated
	 */
	private BigDecimal minattackspeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.MaxAttackSpeed
	 * @mbggenerated
	 */
	private BigDecimal maxattackspeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.MinAttack
	 * @mbggenerated
	 */
	private Integer minattack;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.MaxAttack
	 * @mbggenerated
	 */
	private Integer maxattack;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.MinHP
	 * @mbggenerated
	 */
	private Integer minhp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.MaxHP
	 * @mbggenerated
	 */
	private Integer maxhp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.MinMoveSpeed
	 * @mbggenerated
	 */
	private Integer minmovespeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.MaxMoveSpeed
	 * @mbggenerated
	 */
	private Integer maxmovespeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.Icon
	 * @mbggenerated
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_sylphbeast.Model
	 * @mbggenerated
	 */
	private String model;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.ID
	 * @return  the value of mt_s_sylphbeast.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.ID
	 * @param id  the value for mt_s_sylphbeast.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.Name
	 * @return  the value of mt_s_sylphbeast.Name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.Name
	 * @param name  the value for mt_s_sylphbeast.Name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.Star
	 * @return  the value of mt_s_sylphbeast.Star
	 * @mbggenerated
	 */
	public Integer getStar() {
		return star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.Star
	 * @param star  the value for mt_s_sylphbeast.Star
	 * @mbggenerated
	 */
	public void setStar(Integer star) {
		this.star = star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.RadarUnlockGrade
	 * @return  the value of mt_s_sylphbeast.RadarUnlockGrade
	 * @mbggenerated
	 */
	public Integer getRadarunlockgrade() {
		return radarunlockgrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.RadarUnlockGrade
	 * @param radarunlockgrade  the value for mt_s_sylphbeast.RadarUnlockGrade
	 * @mbggenerated
	 */
	public void setRadarunlockgrade(Integer radarunlockgrade) {
		this.radarunlockgrade = radarunlockgrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.SylphBeastStoreGrade
	 * @return  the value of mt_s_sylphbeast.SylphBeastStoreGrade
	 * @mbggenerated
	 */
	public Integer getSylphbeaststoregrade() {
		return sylphbeaststoregrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.SylphBeastStoreGrade
	 * @param sylphbeaststoregrade  the value for mt_s_sylphbeast.SylphBeastStoreGrade
	 * @mbggenerated
	 */
	public void setSylphbeaststoregrade(Integer sylphbeaststoregrade) {
		this.sylphbeaststoregrade = sylphbeaststoregrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.AttackTypeID
	 * @return  the value of mt_s_sylphbeast.AttackTypeID
	 * @mbggenerated
	 */
	public Integer getAttacktypeid() {
		return attacktypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.AttackTypeID
	 * @param attacktypeid  the value for mt_s_sylphbeast.AttackTypeID
	 * @mbggenerated
	 */
	public void setAttacktypeid(Integer attacktypeid) {
		this.attacktypeid = attacktypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.MinAttackSpeed
	 * @return  the value of mt_s_sylphbeast.MinAttackSpeed
	 * @mbggenerated
	 */
	public BigDecimal getMinattackspeed() {
		return minattackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.MinAttackSpeed
	 * @param minattackspeed  the value for mt_s_sylphbeast.MinAttackSpeed
	 * @mbggenerated
	 */
	public void setMinattackspeed(BigDecimal minattackspeed) {
		this.minattackspeed = minattackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.MaxAttackSpeed
	 * @return  the value of mt_s_sylphbeast.MaxAttackSpeed
	 * @mbggenerated
	 */
	public BigDecimal getMaxattackspeed() {
		return maxattackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.MaxAttackSpeed
	 * @param maxattackspeed  the value for mt_s_sylphbeast.MaxAttackSpeed
	 * @mbggenerated
	 */
	public void setMaxattackspeed(BigDecimal maxattackspeed) {
		this.maxattackspeed = maxattackspeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.MinAttack
	 * @return  the value of mt_s_sylphbeast.MinAttack
	 * @mbggenerated
	 */
	public Integer getMinattack() {
		return minattack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.MinAttack
	 * @param minattack  the value for mt_s_sylphbeast.MinAttack
	 * @mbggenerated
	 */
	public void setMinattack(Integer minattack) {
		this.minattack = minattack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.MaxAttack
	 * @return  the value of mt_s_sylphbeast.MaxAttack
	 * @mbggenerated
	 */
	public Integer getMaxattack() {
		return maxattack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.MaxAttack
	 * @param maxattack  the value for mt_s_sylphbeast.MaxAttack
	 * @mbggenerated
	 */
	public void setMaxattack(Integer maxattack) {
		this.maxattack = maxattack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.MinHP
	 * @return  the value of mt_s_sylphbeast.MinHP
	 * @mbggenerated
	 */
	public Integer getMinhp() {
		return minhp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.MinHP
	 * @param minhp  the value for mt_s_sylphbeast.MinHP
	 * @mbggenerated
	 */
	public void setMinhp(Integer minhp) {
		this.minhp = minhp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.MaxHP
	 * @return  the value of mt_s_sylphbeast.MaxHP
	 * @mbggenerated
	 */
	public Integer getMaxhp() {
		return maxhp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.MaxHP
	 * @param maxhp  the value for mt_s_sylphbeast.MaxHP
	 * @mbggenerated
	 */
	public void setMaxhp(Integer maxhp) {
		this.maxhp = maxhp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.MinMoveSpeed
	 * @return  the value of mt_s_sylphbeast.MinMoveSpeed
	 * @mbggenerated
	 */
	public Integer getMinmovespeed() {
		return minmovespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.MinMoveSpeed
	 * @param minmovespeed  the value for mt_s_sylphbeast.MinMoveSpeed
	 * @mbggenerated
	 */
	public void setMinmovespeed(Integer minmovespeed) {
		this.minmovespeed = minmovespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.MaxMoveSpeed
	 * @return  the value of mt_s_sylphbeast.MaxMoveSpeed
	 * @mbggenerated
	 */
	public Integer getMaxmovespeed() {
		return maxmovespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.MaxMoveSpeed
	 * @param maxmovespeed  the value for mt_s_sylphbeast.MaxMoveSpeed
	 * @mbggenerated
	 */
	public void setMaxmovespeed(Integer maxmovespeed) {
		this.maxmovespeed = maxmovespeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.Icon
	 * @return  the value of mt_s_sylphbeast.Icon
	 * @mbggenerated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.Icon
	 * @param icon  the value for mt_s_sylphbeast.Icon
	 * @mbggenerated
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_sylphbeast.Model
	 * @return  the value of mt_s_sylphbeast.Model
	 * @mbggenerated
	 */
	public String getModel() {
		return model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_sylphbeast.Model
	 * @param model  the value for mt_s_sylphbeast.Model
	 * @mbggenerated
	 */
	public void setModel(String model) {
		this.model = model;
	}
}