package com.mytribe.db.entity.strategy;

public class TypeStarColumnUnlockColumnTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_type_star_column_unlockcolumn.Type
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_type_star_column_unlockcolumn.Star
	 * @mbggenerated
	 */
	private Integer star;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_type_star_column_unlockcolumn.NewCoulumnID
	 * @mbggenerated
	 */
	private Integer newcoulumnid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_type_star_column_unlockcolumn.ItemID
	 * @mbggenerated
	 */
	private Integer itemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_s_type_star_column_unlockcolumn.Num
	 * @mbggenerated
	 */
	private Integer num;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_type_star_column_unlockcolumn.Type
	 * @return  the value of mt_s_type_star_column_unlockcolumn.Type
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_type_star_column_unlockcolumn.Type
	 * @param type  the value for mt_s_type_star_column_unlockcolumn.Type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_type_star_column_unlockcolumn.Star
	 * @return  the value of mt_s_type_star_column_unlockcolumn.Star
	 * @mbggenerated
	 */
	public Integer getStar() {
		return star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_type_star_column_unlockcolumn.Star
	 * @param star  the value for mt_s_type_star_column_unlockcolumn.Star
	 * @mbggenerated
	 */
	public void setStar(Integer star) {
		this.star = star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_type_star_column_unlockcolumn.NewCoulumnID
	 * @return  the value of mt_s_type_star_column_unlockcolumn.NewCoulumnID
	 * @mbggenerated
	 */
	public Integer getNewcoulumnid() {
		return newcoulumnid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_type_star_column_unlockcolumn.NewCoulumnID
	 * @param newcoulumnid  the value for mt_s_type_star_column_unlockcolumn.NewCoulumnID
	 * @mbggenerated
	 */
	public void setNewcoulumnid(Integer newcoulumnid) {
		this.newcoulumnid = newcoulumnid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_type_star_column_unlockcolumn.ItemID
	 * @return  the value of mt_s_type_star_column_unlockcolumn.ItemID
	 * @mbggenerated
	 */
	public Integer getItemid() {
		return itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_type_star_column_unlockcolumn.ItemID
	 * @param itemid  the value for mt_s_type_star_column_unlockcolumn.ItemID
	 * @mbggenerated
	 */
	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_s_type_star_column_unlockcolumn.Num
	 * @return  the value of mt_s_type_star_column_unlockcolumn.Num
	 * @mbggenerated
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_s_type_star_column_unlockcolumn.Num
	 * @param num  the value for mt_s_type_star_column_unlockcolumn.Num
	 * @mbggenerated
	 */
	public void setNum(Integer num) {
		this.num = num;
	}
}