package com.mytribe.db.entity.strategy;

import java.util.ArrayList;
import java.util.List;

public class TypeStarColumnUnlockColumnTemplateExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public TypeStarColumnUnlockColumnTemplateExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTypeIsNull() {
			addCriterion("\"Type\" is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("\"Type\" is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("\"Type\" =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("\"Type\" <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("\"Type\" >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("\"Type\" >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("\"Type\" <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("\"Type\" <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("\"Type\" in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("\"Type\" not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("\"Type\" between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("\"Type\" not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andStarIsNull() {
			addCriterion("Star is null");
			return (Criteria) this;
		}

		public Criteria andStarIsNotNull() {
			addCriterion("Star is not null");
			return (Criteria) this;
		}

		public Criteria andStarEqualTo(Integer value) {
			addCriterion("Star =", value, "star");
			return (Criteria) this;
		}

		public Criteria andStarNotEqualTo(Integer value) {
			addCriterion("Star <>", value, "star");
			return (Criteria) this;
		}

		public Criteria andStarGreaterThan(Integer value) {
			addCriterion("Star >", value, "star");
			return (Criteria) this;
		}

		public Criteria andStarGreaterThanOrEqualTo(Integer value) {
			addCriterion("Star >=", value, "star");
			return (Criteria) this;
		}

		public Criteria andStarLessThan(Integer value) {
			addCriterion("Star <", value, "star");
			return (Criteria) this;
		}

		public Criteria andStarLessThanOrEqualTo(Integer value) {
			addCriterion("Star <=", value, "star");
			return (Criteria) this;
		}

		public Criteria andStarIn(List<Integer> values) {
			addCriterion("Star in", values, "star");
			return (Criteria) this;
		}

		public Criteria andStarNotIn(List<Integer> values) {
			addCriterion("Star not in", values, "star");
			return (Criteria) this;
		}

		public Criteria andStarBetween(Integer value1, Integer value2) {
			addCriterion("Star between", value1, value2, "star");
			return (Criteria) this;
		}

		public Criteria andStarNotBetween(Integer value1, Integer value2) {
			addCriterion("Star not between", value1, value2, "star");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidIsNull() {
			addCriterion("NewCoulumnID is null");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidIsNotNull() {
			addCriterion("NewCoulumnID is not null");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidEqualTo(Integer value) {
			addCriterion("NewCoulumnID =", value, "newcoulumnid");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidNotEqualTo(Integer value) {
			addCriterion("NewCoulumnID <>", value, "newcoulumnid");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidGreaterThan(Integer value) {
			addCriterion("NewCoulumnID >", value, "newcoulumnid");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidGreaterThanOrEqualTo(Integer value) {
			addCriterion("NewCoulumnID >=", value, "newcoulumnid");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidLessThan(Integer value) {
			addCriterion("NewCoulumnID <", value, "newcoulumnid");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidLessThanOrEqualTo(Integer value) {
			addCriterion("NewCoulumnID <=", value, "newcoulumnid");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidIn(List<Integer> values) {
			addCriterion("NewCoulumnID in", values, "newcoulumnid");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidNotIn(List<Integer> values) {
			addCriterion("NewCoulumnID not in", values, "newcoulumnid");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidBetween(Integer value1, Integer value2) {
			addCriterion("NewCoulumnID between", value1, value2, "newcoulumnid");
			return (Criteria) this;
		}

		public Criteria andNewcoulumnidNotBetween(Integer value1, Integer value2) {
			addCriterion("NewCoulumnID not between", value1, value2, "newcoulumnid");
			return (Criteria) this;
		}

		public Criteria andItemidIsNull() {
			addCriterion("ItemID is null");
			return (Criteria) this;
		}

		public Criteria andItemidIsNotNull() {
			addCriterion("ItemID is not null");
			return (Criteria) this;
		}

		public Criteria andItemidEqualTo(Integer value) {
			addCriterion("ItemID =", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotEqualTo(Integer value) {
			addCriterion("ItemID <>", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidGreaterThan(Integer value) {
			addCriterion("ItemID >", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidGreaterThanOrEqualTo(Integer value) {
			addCriterion("ItemID >=", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidLessThan(Integer value) {
			addCriterion("ItemID <", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidLessThanOrEqualTo(Integer value) {
			addCriterion("ItemID <=", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidIn(List<Integer> values) {
			addCriterion("ItemID in", values, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotIn(List<Integer> values) {
			addCriterion("ItemID not in", values, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidBetween(Integer value1, Integer value2) {
			addCriterion("ItemID between", value1, value2, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotBetween(Integer value1, Integer value2) {
			addCriterion("ItemID not between", value1, value2, "itemid");
			return (Criteria) this;
		}

		public Criteria andNumIsNull() {
			addCriterion("Num is null");
			return (Criteria) this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("Num is not null");
			return (Criteria) this;
		}

		public Criteria andNumEqualTo(Integer value) {
			addCriterion("Num =", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotEqualTo(Integer value) {
			addCriterion("Num <>", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThan(Integer value) {
			addCriterion("Num >", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("Num >=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThan(Integer value) {
			addCriterion("Num <", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThanOrEqualTo(Integer value) {
			addCriterion("Num <=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumIn(List<Integer> values) {
			addCriterion("Num in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotIn(List<Integer> values) {
			addCriterion("Num not in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumBetween(Integer value1, Integer value2) {
			addCriterion("Num between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotBetween(Integer value1, Integer value2) {
			addCriterion("Num not between", value1, value2, "num");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mt_s_type_star_column_unlockcolumn
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}