package com.mytribe.db.entity.strategy;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserInfoEntityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public UserInfoEntityExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPlayerIdIsNull() {
			addCriterion("player_id is null");
			return (Criteria) this;
		}

		public Criteria andPlayerIdIsNotNull() {
			addCriterion("player_id is not null");
			return (Criteria) this;
		}

		public Criteria andPlayerIdEqualTo(Integer value) {
			addCriterion("player_id =", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotEqualTo(Integer value) {
			addCriterion("player_id <>", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdGreaterThan(Integer value) {
			addCriterion("player_id >", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("player_id >=", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdLessThan(Integer value) {
			addCriterion("player_id <", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdLessThanOrEqualTo(Integer value) {
			addCriterion("player_id <=", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdIn(List<Integer> values) {
			addCriterion("player_id in", values, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotIn(List<Integer> values) {
			addCriterion("player_id not in", values, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdBetween(Integer value1, Integer value2) {
			addCriterion("player_id between", value1, value2, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("player_id not between", value1, value2, "playerId");
			return (Criteria) this;
		}

		public Criteria andAccountNameIsNull() {
			addCriterion("account_name is null");
			return (Criteria) this;
		}

		public Criteria andAccountNameIsNotNull() {
			addCriterion("account_name is not null");
			return (Criteria) this;
		}

		public Criteria andAccountNameEqualTo(String value) {
			addCriterion("account_name =", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotEqualTo(String value) {
			addCriterion("account_name <>", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameGreaterThan(String value) {
			addCriterion("account_name >", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameGreaterThanOrEqualTo(String value) {
			addCriterion("account_name >=", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLessThan(String value) {
			addCriterion("account_name <", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLessThanOrEqualTo(String value) {
			addCriterion("account_name <=", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLike(String value) {
			addCriterion("account_name like", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotLike(String value) {
			addCriterion("account_name not like", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameIn(List<String> values) {
			addCriterion("account_name in", values, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotIn(List<String> values) {
			addCriterion("account_name not in", values, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameBetween(String value1, String value2) {
			addCriterion("account_name between", value1, value2, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotBetween(String value1, String value2) {
			addCriterion("account_name not between", value1, value2, "accountName");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIsNull() {
			addCriterion("platform_type is null");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIsNotNull() {
			addCriterion("platform_type is not null");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeEqualTo(Integer value) {
			addCriterion("platform_type =", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotEqualTo(Integer value) {
			addCriterion("platform_type <>", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeGreaterThan(Integer value) {
			addCriterion("platform_type >", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("platform_type >=", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeLessThan(Integer value) {
			addCriterion("platform_type <", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeLessThanOrEqualTo(Integer value) {
			addCriterion("platform_type <=", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIn(List<Integer> values) {
			addCriterion("platform_type in", values, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotIn(List<Integer> values) {
			addCriterion("platform_type not in", values, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeBetween(Integer value1, Integer value2) {
			addCriterion("platform_type between", value1, value2, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("platform_type not between", value1, value2, "platformType");
			return (Criteria) this;
		}

		public Criteria andPasswdIsNull() {
			addCriterion("passwd is null");
			return (Criteria) this;
		}

		public Criteria andPasswdIsNotNull() {
			addCriterion("passwd is not null");
			return (Criteria) this;
		}

		public Criteria andPasswdEqualTo(String value) {
			addCriterion("passwd =", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdNotEqualTo(String value) {
			addCriterion("passwd <>", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdGreaterThan(String value) {
			addCriterion("passwd >", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdGreaterThanOrEqualTo(String value) {
			addCriterion("passwd >=", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdLessThan(String value) {
			addCriterion("passwd <", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdLessThanOrEqualTo(String value) {
			addCriterion("passwd <=", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdLike(String value) {
			addCriterion("passwd like", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdNotLike(String value) {
			addCriterion("passwd not like", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdIn(List<String> values) {
			addCriterion("passwd in", values, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdNotIn(List<String> values) {
			addCriterion("passwd not in", values, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdBetween(String value1, String value2) {
			addCriterion("passwd between", value1, value2, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdNotBetween(String value1, String value2) {
			addCriterion("passwd not between", value1, value2, "passwd");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andChargeDateIsNull() {
			addCriterion("charge_date is null");
			return (Criteria) this;
		}

		public Criteria andChargeDateIsNotNull() {
			addCriterion("charge_date is not null");
			return (Criteria) this;
		}

		public Criteria andChargeDateEqualTo(Date value) {
			addCriterion("charge_date =", value, "chargeDate");
			return (Criteria) this;
		}

		public Criteria andChargeDateNotEqualTo(Date value) {
			addCriterion("charge_date <>", value, "chargeDate");
			return (Criteria) this;
		}

		public Criteria andChargeDateGreaterThan(Date value) {
			addCriterion("charge_date >", value, "chargeDate");
			return (Criteria) this;
		}

		public Criteria andChargeDateGreaterThanOrEqualTo(Date value) {
			addCriterion("charge_date >=", value, "chargeDate");
			return (Criteria) this;
		}

		public Criteria andChargeDateLessThan(Date value) {
			addCriterion("charge_date <", value, "chargeDate");
			return (Criteria) this;
		}

		public Criteria andChargeDateLessThanOrEqualTo(Date value) {
			addCriterion("charge_date <=", value, "chargeDate");
			return (Criteria) this;
		}

		public Criteria andChargeDateIn(List<Date> values) {
			addCriterion("charge_date in", values, "chargeDate");
			return (Criteria) this;
		}

		public Criteria andChargeDateNotIn(List<Date> values) {
			addCriterion("charge_date not in", values, "chargeDate");
			return (Criteria) this;
		}

		public Criteria andChargeDateBetween(Date value1, Date value2) {
			addCriterion("charge_date between", value1, value2, "chargeDate");
			return (Criteria) this;
		}

		public Criteria andChargeDateNotBetween(Date value1, Date value2) {
			addCriterion("charge_date not between", value1, value2, "chargeDate");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateIsNull() {
			addCriterion("last_login_date is null");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateIsNotNull() {
			addCriterion("last_login_date is not null");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateEqualTo(Date value) {
			addCriterion("last_login_date =", value, "lastLoginDate");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateNotEqualTo(Date value) {
			addCriterion("last_login_date <>", value, "lastLoginDate");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateGreaterThan(Date value) {
			addCriterion("last_login_date >", value, "lastLoginDate");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateGreaterThanOrEqualTo(Date value) {
			addCriterion("last_login_date >=", value, "lastLoginDate");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateLessThan(Date value) {
			addCriterion("last_login_date <", value, "lastLoginDate");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateLessThanOrEqualTo(Date value) {
			addCriterion("last_login_date <=", value, "lastLoginDate");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateIn(List<Date> values) {
			addCriterion("last_login_date in", values, "lastLoginDate");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateNotIn(List<Date> values) {
			addCriterion("last_login_date not in", values, "lastLoginDate");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateBetween(Date value1, Date value2) {
			addCriterion("last_login_date between", value1, value2, "lastLoginDate");
			return (Criteria) this;
		}

		public Criteria andLastLoginDateNotBetween(Date value1, Date value2) {
			addCriterion("last_login_date not between", value1, value2, "lastLoginDate");
			return (Criteria) this;
		}

		public Criteria andActiveIpIsNull() {
			addCriterion("active_ip is null");
			return (Criteria) this;
		}

		public Criteria andActiveIpIsNotNull() {
			addCriterion("active_ip is not null");
			return (Criteria) this;
		}

		public Criteria andActiveIpEqualTo(String value) {
			addCriterion("active_ip =", value, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpNotEqualTo(String value) {
			addCriterion("active_ip <>", value, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpGreaterThan(String value) {
			addCriterion("active_ip >", value, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpGreaterThanOrEqualTo(String value) {
			addCriterion("active_ip >=", value, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpLessThan(String value) {
			addCriterion("active_ip <", value, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpLessThanOrEqualTo(String value) {
			addCriterion("active_ip <=", value, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpLike(String value) {
			addCriterion("active_ip like", value, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpNotLike(String value) {
			addCriterion("active_ip not like", value, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpIn(List<String> values) {
			addCriterion("active_ip in", values, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpNotIn(List<String> values) {
			addCriterion("active_ip not in", values, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpBetween(String value1, String value2) {
			addCriterion("active_ip between", value1, value2, "activeIp");
			return (Criteria) this;
		}

		public Criteria andActiveIpNotBetween(String value1, String value2) {
			addCriterion("active_ip not between", value1, value2, "activeIp");
			return (Criteria) this;
		}

		public Criteria andLockedReasonIsNull() {
			addCriterion("locked_reason is null");
			return (Criteria) this;
		}

		public Criteria andLockedReasonIsNotNull() {
			addCriterion("locked_reason is not null");
			return (Criteria) this;
		}

		public Criteria andLockedReasonEqualTo(String value) {
			addCriterion("locked_reason =", value, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonNotEqualTo(String value) {
			addCriterion("locked_reason <>", value, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonGreaterThan(String value) {
			addCriterion("locked_reason >", value, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonGreaterThanOrEqualTo(String value) {
			addCriterion("locked_reason >=", value, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonLessThan(String value) {
			addCriterion("locked_reason <", value, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonLessThanOrEqualTo(String value) {
			addCriterion("locked_reason <=", value, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonLike(String value) {
			addCriterion("locked_reason like", value, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonNotLike(String value) {
			addCriterion("locked_reason not like", value, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonIn(List<String> values) {
			addCriterion("locked_reason in", values, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonNotIn(List<String> values) {
			addCriterion("locked_reason not in", values, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonBetween(String value1, String value2) {
			addCriterion("locked_reason between", value1, value2, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andLockedReasonNotBetween(String value1, String value2) {
			addCriterion("locked_reason not between", value1, value2, "lockedReason");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateIsNull() {
			addCriterion("unlocked_date is null");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateIsNotNull() {
			addCriterion("unlocked_date is not null");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateEqualTo(Date value) {
			addCriterion("unlocked_date =", value, "unlockedDate");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateNotEqualTo(Date value) {
			addCriterion("unlocked_date <>", value, "unlockedDate");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateGreaterThan(Date value) {
			addCriterion("unlocked_date >", value, "unlockedDate");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("unlocked_date >=", value, "unlockedDate");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateLessThan(Date value) {
			addCriterion("unlocked_date <", value, "unlockedDate");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateLessThanOrEqualTo(Date value) {
			addCriterion("unlocked_date <=", value, "unlockedDate");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateIn(List<Date> values) {
			addCriterion("unlocked_date in", values, "unlockedDate");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateNotIn(List<Date> values) {
			addCriterion("unlocked_date not in", values, "unlockedDate");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateBetween(Date value1, Date value2) {
			addCriterion("unlocked_date between", value1, value2, "unlockedDate");
			return (Criteria) this;
		}

		public Criteria andUnlockedDateNotBetween(Date value1, Date value2) {
			addCriterion("unlocked_date not between", value1, value2, "unlockedDate");
			return (Criteria) this;
		}

		public Criteria andIsGmIsNull() {
			addCriterion("is_gm is null");
			return (Criteria) this;
		}

		public Criteria andIsGmIsNotNull() {
			addCriterion("is_gm is not null");
			return (Criteria) this;
		}

		public Criteria andIsGmEqualTo(Boolean value) {
			addCriterion("is_gm =", value, "isGm");
			return (Criteria) this;
		}

		public Criteria andIsGmNotEqualTo(Boolean value) {
			addCriterion("is_gm <>", value, "isGm");
			return (Criteria) this;
		}

		public Criteria andIsGmGreaterThan(Boolean value) {
			addCriterion("is_gm >", value, "isGm");
			return (Criteria) this;
		}

		public Criteria andIsGmGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_gm >=", value, "isGm");
			return (Criteria) this;
		}

		public Criteria andIsGmLessThan(Boolean value) {
			addCriterion("is_gm <", value, "isGm");
			return (Criteria) this;
		}

		public Criteria andIsGmLessThanOrEqualTo(Boolean value) {
			addCriterion("is_gm <=", value, "isGm");
			return (Criteria) this;
		}

		public Criteria andIsGmIn(List<Boolean> values) {
			addCriterion("is_gm in", values, "isGm");
			return (Criteria) this;
		}

		public Criteria andIsGmNotIn(List<Boolean> values) {
			addCriterion("is_gm not in", values, "isGm");
			return (Criteria) this;
		}

		public Criteria andIsGmBetween(Boolean value1, Boolean value2) {
			addCriterion("is_gm between", value1, value2, "isGm");
			return (Criteria) this;
		}

		public Criteria andIsGmNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_gm not between", value1, value2, "isGm");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyIsNull() {
			addCriterion("locale_key is null");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyIsNotNull() {
			addCriterion("locale_key is not null");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyEqualTo(Byte value) {
			addCriterion("locale_key =", value, "localeKey");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyNotEqualTo(Byte value) {
			addCriterion("locale_key <>", value, "localeKey");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyGreaterThan(Byte value) {
			addCriterion("locale_key >", value, "localeKey");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyGreaterThanOrEqualTo(Byte value) {
			addCriterion("locale_key >=", value, "localeKey");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyLessThan(Byte value) {
			addCriterion("locale_key <", value, "localeKey");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyLessThanOrEqualTo(Byte value) {
			addCriterion("locale_key <=", value, "localeKey");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyIn(List<Byte> values) {
			addCriterion("locale_key in", values, "localeKey");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyNotIn(List<Byte> values) {
			addCriterion("locale_key not in", values, "localeKey");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyBetween(Byte value1, Byte value2) {
			addCriterion("locale_key between", value1, value2, "localeKey");
			return (Criteria) this;
		}

		public Criteria andLocaleKeyNotBetween(Byte value1, Byte value2) {
			addCriterion("locale_key not between", value1, value2, "localeKey");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mt_u_userinfo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}