package com.mytribe.db.mapper.user;

import com.mytribe.db.entity.user.ServerListEntity;
import com.mytribe.db.entity.user.ServerListEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServerListEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int countByExample(ServerListEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int deleteByExample(ServerListEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int insert(ServerListEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int insertSelective(ServerListEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	List<ServerListEntity> selectByExample(ServerListEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	ServerListEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ServerListEntity record, @Param("example") ServerListEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int updateByExample(@Param("record") ServerListEntity record, @Param("example") ServerListEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int updateByPrimaryKeySelective(ServerListEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int updateByPrimaryKey(ServerListEntity record);
}