package com.mytribe.db.mapper.user;

import com.mytribe.common.UserCount;
import com.mytribe.db.entity.user.UserEntity;
import com.mytribe.db.entity.user.UserEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int countByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int deleteByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int insert(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int insertSelective(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	List<UserEntity> selectByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	UserEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int updateByExampleSelective(@Param("record") UserEntity record, @Param("example") UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int updateByExample(@Param("record") UserEntity record, @Param("example") UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int updateByPrimaryKeySelective(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_user
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	int updateByPrimaryKey(UserEntity record);
	
	List<UserCount> userCountByServerId();
}