package com.mytribe.db.entity.user;

public class ServerListEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.server_id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private String serverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.app_id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private Integer appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.ip_address
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private String ipAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.server_name
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private String serverName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.status_type
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private Integer statusType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.description
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.sorted
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private Integer sorted;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.id
	 * @return  the value of server_list.id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.id
	 * @param id  the value for server_list.id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.server_id
	 * @return  the value of server_list.server_id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public String getServerId() {
		return serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.server_id
	 * @param serverId  the value for server_list.server_id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setServerId(String serverId) {
		this.serverId = serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.app_id
	 * @return  the value of server_list.app_id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public Integer getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.app_id
	 * @param appId  the value for server_list.app_id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.ip_address
	 * @return  the value of server_list.ip_address
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public String getIpAddress() {
		return ipAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.ip_address
	 * @param ipAddress  the value for server_list.ip_address
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.server_name
	 * @return  the value of server_list.server_name
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public String getServerName() {
		return serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.server_name
	 * @param serverName  the value for server_list.server_name
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.status_type
	 * @return  the value of server_list.status_type
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public Integer getStatusType() {
		return statusType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.status_type
	 * @param statusType  the value for server_list.status_type
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setStatusType(Integer statusType) {
		this.statusType = statusType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.description
	 * @return  the value of server_list.description
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.description
	 * @param description  the value for server_list.description
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.sorted
	 * @return  the value of server_list.sorted
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public Integer getSorted() {
		return sorted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.sorted
	 * @param sorted  the value for server_list.sorted
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setSorted(Integer sorted) {
		this.sorted = sorted;
	}
}