package com.mytribe.db.entity.user;

public class UserEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_user.id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_user.account_name
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private String accountName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_user.platform_type
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private Integer platformType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mt_u_user.server_id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	private String serverId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_user.id
	 * @return  the value of mt_u_user.id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_user.id
	 * @param id  the value for mt_u_user.id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_user.account_name
	 * @return  the value of mt_u_user.account_name
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public String getAccountName() {
		return accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_user.account_name
	 * @param accountName  the value for mt_u_user.account_name
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_user.platform_type
	 * @return  the value of mt_u_user.platform_type
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public Integer getPlatformType() {
		return platformType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_user.platform_type
	 * @param platformType  the value for mt_u_user.platform_type
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setPlatformType(Integer platformType) {
		this.platformType = platformType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mt_u_user.server_id
	 * @return  the value of mt_u_user.server_id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public String getServerId() {
		return serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mt_u_user.server_id
	 * @param serverId  the value for mt_u_user.server_id
	 * @mbggenerated  Tue May 16 11:56:52 CST 2017
	 */
	public void setServerId(String serverId) {
		this.serverId = serverId;
	}
}