package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.AttackTypeTemplate;
import com.mytribe.db.entity.strategy.AttackTypeTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttackTypeTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	int countByExample(AttackTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	int deleteByExample(AttackTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	int insert(AttackTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	int insertSelective(AttackTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	List<AttackTypeTemplate> selectByExample(AttackTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	AttackTypeTemplate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AttackTypeTemplate record, @Param("example") AttackTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AttackTypeTemplate record, @Param("example") AttackTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AttackTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_attacktype
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AttackTypeTemplate record);
}