package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.BuildingTypeTemplate;
import com.mytribe.db.entity.strategy.BuildingTypeTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuildingTypeTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	int countByExample(BuildingTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	int deleteByExample(BuildingTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer buildingtypeid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	int insert(BuildingTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	int insertSelective(BuildingTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	List<BuildingTypeTemplate> selectByExample(BuildingTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	BuildingTypeTemplate selectByPrimaryKey(Integer buildingtypeid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") BuildingTypeTemplate record, @Param("example") BuildingTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") BuildingTypeTemplate record, @Param("example") BuildingTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(BuildingTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildingtype
	 * @mbggenerated
	 */
	int updateByPrimaryKey(BuildingTypeTemplate record);
}