package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.BuildingGradeTemplate;
import com.mytribe.db.entity.strategy.BuildingGradeTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuildingGradeTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	int countByExample(BuildingGradeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	int deleteByExample(BuildingGradeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	int insert(BuildingGradeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	int insertSelective(BuildingGradeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	List<BuildingGradeTemplate> selectByExample(BuildingGradeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	BuildingGradeTemplate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") BuildingGradeTemplate record, @Param("example") BuildingGradeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") BuildingGradeTemplate record, @Param("example") BuildingGradeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(BuildingGradeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_buildinggrade
	 * @mbggenerated
	 */
	int updateByPrimaryKey(BuildingGradeTemplate record);
}