package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.EquipTypeTemplate;
import com.mytribe.db.entity.strategy.EquipTypeTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquipTypeTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	int countByExample(EquipTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	int deleteByExample(EquipTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	int insert(EquipTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	int insertSelective(EquipTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	List<EquipTypeTemplate> selectByExample(EquipTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	EquipTypeTemplate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") EquipTypeTemplate record, @Param("example") EquipTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") EquipTypeTemplate record, @Param("example") EquipTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(EquipTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_equiptype
	 * @mbggenerated
	 */
	int updateByPrimaryKey(EquipTypeTemplate record);
}