package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.GradeExpTemplate;
import com.mytribe.db.entity.strategy.GradeExpTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GradeExpTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_grade_exp
	 * @mbggenerated
	 */
	int countByExample(GradeExpTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_grade_exp
	 * @mbggenerated
	 */
	int deleteByExample(GradeExpTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_grade_exp
	 * @mbggenerated
	 */
	int insert(GradeExpTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_grade_exp
	 * @mbggenerated
	 */
	int insertSelective(GradeExpTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_grade_exp
	 * @mbggenerated
	 */
	List<GradeExpTemplate> selectByExample(GradeExpTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_grade_exp
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") GradeExpTemplate record, @Param("example") GradeExpTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_grade_exp
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") GradeExpTemplate record, @Param("example") GradeExpTemplateExample example);
}