package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.ItemTemplate;
import com.mytribe.db.entity.strategy.ItemTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	int countByExample(ItemTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	int deleteByExample(ItemTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer itemid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	int insert(ItemTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	int insertSelective(ItemTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	List<ItemTemplate> selectByExample(ItemTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	ItemTemplate selectByPrimaryKey(Integer itemid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ItemTemplate record, @Param("example") ItemTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ItemTemplate record, @Param("example") ItemTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ItemTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_item
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ItemTemplate record);
}