package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.MainRoleBaseInfoTemplate;
import com.mytribe.db.entity.strategy.MainRoleBaseInfoTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MainRoleBaseInfoTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_mainrolebaseinfo
	 * @mbggenerated
	 */
	int countByExample(MainRoleBaseInfoTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_mainrolebaseinfo
	 * @mbggenerated
	 */
	int deleteByExample(MainRoleBaseInfoTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_mainrolebaseinfo
	 * @mbggenerated
	 */
	int insert(MainRoleBaseInfoTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_mainrolebaseinfo
	 * @mbggenerated
	 */
	int insertSelective(MainRoleBaseInfoTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_mainrolebaseinfo
	 * @mbggenerated
	 */
	List<MainRoleBaseInfoTemplate> selectByExample(MainRoleBaseInfoTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_mainrolebaseinfo
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") MainRoleBaseInfoTemplate record, @Param("example") MainRoleBaseInfoTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_mainrolebaseinfo
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") MainRoleBaseInfoTemplate record, @Param("example") MainRoleBaseInfoTemplateExample example);
}