package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.MedalRankEntity;
import com.mytribe.db.entity.strategy.MedalRankEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MedalRankEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	int countByExample(MedalRankEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	int deleteByExample(MedalRankEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer rankid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	int insert(MedalRankEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	int insertSelective(MedalRankEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	List<MedalRankEntity> selectByExample(MedalRankEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	MedalRankEntity selectByPrimaryKey(Integer rankid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") MedalRankEntity record, @Param("example") MedalRankEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") MedalRankEntity record, @Param("example") MedalRankEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(MedalRankEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_medalrank
	 * @mbggenerated
	 */
	int updateByPrimaryKey(MedalRankEntity record);
}