package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.PlayerSylphbeastEntity;
import com.mytribe.db.entity.strategy.PlayerSylphbeastEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayerSylphbeastEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	int countByExample(PlayerSylphbeastEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	int deleteByExample(PlayerSylphbeastEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	int insert(PlayerSylphbeastEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	int insertSelective(PlayerSylphbeastEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	List<PlayerSylphbeastEntity> selectByExample(PlayerSylphbeastEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	PlayerSylphbeastEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") PlayerSylphbeastEntity record, @Param("example") PlayerSylphbeastEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") PlayerSylphbeastEntity record, @Param("example") PlayerSylphbeastEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PlayerSylphbeastEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_sylphbeast
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PlayerSylphbeastEntity record);
}