package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.PlayerInfoEntity;
import com.mytribe.db.entity.strategy.PlayerInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayerInfoEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	int countByExample(PlayerInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	int deleteByExample(PlayerInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer playerid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	int insert(PlayerInfoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	int insertSelective(PlayerInfoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	List<PlayerInfoEntity> selectByExample(PlayerInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	PlayerInfoEntity selectByPrimaryKey(Integer playerid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") PlayerInfoEntity record, @Param("example") PlayerInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") PlayerInfoEntity record, @Param("example") PlayerInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PlayerInfoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_playerinfo
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PlayerInfoEntity record);
}