package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.PlayerItemEntity;
import com.mytribe.db.entity.strategy.PlayerItemEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayerItemEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	int countByExample(PlayerItemEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	int deleteByExample(PlayerItemEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	int insert(PlayerItemEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	int insertSelective(PlayerItemEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	List<PlayerItemEntity> selectByExample(PlayerItemEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	PlayerItemEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") PlayerItemEntity record, @Param("example") PlayerItemEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") PlayerItemEntity record, @Param("example") PlayerItemEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PlayerItemEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_item
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PlayerItemEntity record);
}