package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.PlayerEquipEntity;
import com.mytribe.db.entity.strategy.PlayerEquipEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayerEquipEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	int countByExample(PlayerEquipEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	int deleteByExample(PlayerEquipEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	int insert(PlayerEquipEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	int insertSelective(PlayerEquipEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	List<PlayerEquipEntity> selectByExample(PlayerEquipEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	PlayerEquipEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") PlayerEquipEntity record, @Param("example") PlayerEquipEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") PlayerEquipEntity record, @Param("example") PlayerEquipEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PlayerEquipEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_player_equip
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PlayerEquipEntity record);
}