package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.SkillTypeTemplate;
import com.mytribe.db.entity.strategy.SkillTypeTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkillTypeTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	int countByExample(SkillTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	int deleteByExample(SkillTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	int insert(SkillTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	int insertSelective(SkillTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	List<SkillTypeTemplate> selectByExample(SkillTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	SkillTypeTemplate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SkillTypeTemplate record, @Param("example") SkillTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SkillTypeTemplate record, @Param("example") SkillTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SkillTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_skilltype
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SkillTypeTemplate record);
}