package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.SoldierGradeInfoTemplate;
import com.mytribe.db.entity.strategy.SoldierGradeInfoTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SoldierGradeInfoTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiergradeinfo
	 * @mbggenerated
	 */
	int countByExample(SoldierGradeInfoTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiergradeinfo
	 * @mbggenerated
	 */
	int deleteByExample(SoldierGradeInfoTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiergradeinfo
	 * @mbggenerated
	 */
	int insert(SoldierGradeInfoTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiergradeinfo
	 * @mbggenerated
	 */
	int insertSelective(SoldierGradeInfoTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiergradeinfo
	 * @mbggenerated
	 */
	List<SoldierGradeInfoTemplate> selectByExample(SoldierGradeInfoTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiergradeinfo
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SoldierGradeInfoTemplate record, @Param("example") SoldierGradeInfoTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiergradeinfo
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SoldierGradeInfoTemplate record, @Param("example") SoldierGradeInfoTemplateExample example);
}