package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.SoldierTypeTemplate;
import com.mytribe.db.entity.strategy.SoldierTypeTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SoldierTypeTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiertype
	 * @mbggenerated
	 */
	int countByExample(SoldierTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiertype
	 * @mbggenerated
	 */
	int deleteByExample(SoldierTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiertype
	 * @mbggenerated
	 */
	int insert(SoldierTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiertype
	 * @mbggenerated
	 */
	int insertSelective(SoldierTypeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiertype
	 * @mbggenerated
	 */
	List<SoldierTypeTemplate> selectByExample(SoldierTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiertype
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SoldierTypeTemplate record, @Param("example") SoldierTypeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_soldiertype
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SoldierTypeTemplate record, @Param("example") SoldierTypeTemplateExample example);
}