package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.SylphbeastTemplate;
import com.mytribe.db.entity.strategy.SylphbeastTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SylphbeastTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	int countByExample(SylphbeastTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	int deleteByExample(SylphbeastTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	int insert(SylphbeastTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	int insertSelective(SylphbeastTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	List<SylphbeastTemplate> selectByExample(SylphbeastTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	SylphbeastTemplate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SylphbeastTemplate record, @Param("example") SylphbeastTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SylphbeastTemplate record, @Param("example") SylphbeastTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SylphbeastTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_sylphbeast
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SylphbeastTemplate record);
}