package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.TypeStarColumnUnlockColumnTemplate;
import com.mytribe.db.entity.strategy.TypeStarColumnUnlockColumnTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TypeStarColumnUnlockColumnTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	int countByExample(TypeStarColumnUnlockColumnTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	int deleteByExample(TypeStarColumnUnlockColumnTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	int insert(TypeStarColumnUnlockColumnTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	int insertSelective(TypeStarColumnUnlockColumnTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	List<TypeStarColumnUnlockColumnTemplate> selectByExample(TypeStarColumnUnlockColumnTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") TypeStarColumnUnlockColumnTemplate record, @Param("example") TypeStarColumnUnlockColumnTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_s_type_star_column_unlockcolumn
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") TypeStarColumnUnlockColumnTemplate record, @Param("example") TypeStarColumnUnlockColumnTemplateExample example);
}