package com.mytribe.db.mapper.strategy;

import com.mytribe.db.entity.strategy.UserInfoEntity;
import com.mytribe.db.entity.strategy.UserInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	int countByExample(UserInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	int deleteByExample(UserInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	int insert(UserInfoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	int insertSelective(UserInfoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	List<UserInfoEntity> selectByExample(UserInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	UserInfoEntity selectByPrimaryKey(Integer playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") UserInfoEntity record, @Param("example") UserInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") UserInfoEntity record, @Param("example") UserInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserInfoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mt_u_userinfo
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserInfoEntity record);
}